os: linux
dist: xenial
language: node_js
node_js:
  - 10
services:
  - xvfb
  - mongodb
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
after_script:
  - curl -vLk http://localhost:3001/auth/register